### ISSUE TITLE
Les routes /order ne fonctionnent pas.

### ISSUE THREAD

**Issue by DevonTheFloor** [OpenClassrooms-Student-Center/JWDP5#1]
La requête d'achat du produit revient en erreur, soit 500 pour les routes teddies et furnitures et 400 pour le cameras.
Elle est bien constituées de l'objet contact et du tableau d' id de produit.
Les routes get fonctionnent très bien. Pour la route post on a bien le 200 pour connection au back, mais une erreur est retournbée.
```
let objt = {
   contact :
  {
    prénom: "Jean",
    nom: "Valjan",
    adresse: "ici et pas ailleurs",
    ville: "Paradise City",
    email: "poiudg@hjedfru.gt"
  },
   products :[
  "5be9c4471c9d440000a730e8",
  "5be1ef211c9d44000030b062"
    ]
  }
```

**Comment by willehpeh** [comment]
Bonjour, avez-vous essayé sans l’accent sur le “prénom” ?

**Comment by DevonTheFloor** [comment]
Finalement ça fonctionne en anglais (firstName, lastName etc...). Pas très grave, sauf que c'est pas précisé dans la doc. Merci.

**Comment by MrGyo** [comment]
Sans aller vérifier directement dans l'API c'est effectivement difficile de trouver, j'ai eu le même problème. Cela manque de clarté.
